# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receive_addr',
            field=models.CharField(default='', max_length=30, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receive_name',
            field=models.CharField(default='', max_length=20, verbose_name='收货人姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receive_phone',
            field=models.CharField(default='', max_length=11, verbose_name='收货人手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receive_postcode',
            field=models.CharField(default='', max_length=6, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
