# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('pic', models.ImageField(upload_to='goods', verbose_name='商品预览图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('unit', models.CharField(max_length=10, verbose_name='计量单位')),
                ('intro', models.CharField(max_length=100, verbose_name='商品简介')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('profile', tinymce.models.HTMLField(verbose_name='商品详细介绍')),
                ('click', models.IntegerField(verbose_name='点击量')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '商品详细信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '商品分类',
            },
        ),
    ]
