# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181027_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '商品详细信息', 'verbose_name_plural': '商品详细信息'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
    ]
