# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='receive_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='receive_postcode',
            field=models.CharField(max_length=6),
        ),
    ]
